# .gitlab-ci.yml

stages:
- build
- buildarm
- prepages
- pages

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.ubuntu_install_deps: &ubuntu_install_deps
  - DEBIAN_FRONTEND=noninteractive apt-get update -y
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      make cmake m4 libc-dev clang gcc git valgrind ninja-build gcovr 
      ca-certificates curl libunistring-dev ninja-build

test:
  stage: build
  image: ubuntu
  script: 
  - *ubuntu_install_deps
  - make gitlab_gcc_cdash
  - make gitlab_clang_cdash
  - make test_project

test_arm:
  stage: buildarm
  image: registry.gitlab.com/kamcuk/armbuilder/armbuilder
  script:
  - make gitlab_arm_cdash

pages_repos:
  stage: prepages
  image: docker:stable
  services:
  - docker:stable-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: /certs
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - apk add --no-cache make git bash
  - make pages_repos
  artifacts:
    paths:
    - public/
    expire_in: 1 week

pages:
  stage: pages
  image: ubuntu
  script:
  - *ubuntu_install_deps
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      graphviz doxygen jq
  - make gitlab_pages
  artifacts:
    paths:
    - public

