# .gitlab-ci.yml

stages:
- build
- buildarm
- pages

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.ubuntu_install_deps: &ubuntu_install_deps
  - DEBIAN_FRONTEND=noninteractive apt-get update -y
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      make cmake m4 libc-dev clang gcc git valgrind ninja-build gcovr 
      ca-certificates curl libunistring-dev ninja-build

test:
  stage: build
  image: ubuntu
  script: 
  - *ubuntu_install_deps
  - make gitlab_gcc_cdash
  - make gitlab_clang_cdash
  - make test_project

test_arm:
  stage: buildarm
  image: registry.gitlab.com/kamcuk/armbuilder/armbuilder
  script:
  - make gitlab_arm_cdash

pages:
  stage: pages
  image: ubuntu
  script:
  - *ubuntu_install_deps
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      graphviz doxygen jq
  - make gitlab_pages
  artifacts:
    paths:
    - public

