# .gitlab-ci.yml
---

image: registry.gitlab.com/kamcuk/builder
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CMAKE_BUILD_TYPE: Release

###############################################################################

icc_test:
  tags:
    - perun
  image:
    name: intel/oneapi-hpckit
    entrypoint: []
  variables:
    CC: icc
  script:
    - . /root/.oneapi_env_vars
    - apt update
    - apt install -y git m4 libunistring-dev ninja-build
    - make test

gcc_test:
  variables:
    CC: gcc
  script:
    - make valgrind
    - make test_project

gcc_sanitize_test:
  variables:
    CC: gcc
  script:
    - make MODE=sanitize test

clang_test:
  variables:
    CC: clang
  script:
    - make test

arm_test:
  script:
    - make SYSTEM=arm test

project_add_subdirectory_test:
  script:
    - make test_project_add_subdirectory

alpine_test:
  image: registry.gitlab.com/kamcuk/builder:alpine
  script:
    - make test

pages_build:
  script:
    - make gitlab_pages
  artifacts:
    paths:
      - public/
    expire_in: 1 week

###############################################################################

pages:
  stage: deploy
  image: busybox
  script:
    - find public -type f
  artifacts:
    paths:
      - public/
  only:
    - tags
