# .gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.ubuntu_install_deps: &ubuntu_install_deps
  - DEBIAN_FRONTEND=noninteractive apt-get update -y
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      make cmake m4 libc-dev clang gcc git valgrind ninja-build gcovr

test_project:
  image: ubuntu
  script: 
  - *ubuntu_install_deps
  - make test_project

cdash_gcc:
  image: ubuntu
  script:
  - *ubuntu_install_deps
  - make gitlab_gcc_cdash

cdash_clang:
  image: ubuntu
  script:
  - *ubuntu_install_deps
  - make gitlab_clang_cdash

cdash_arm:
  image: registry.gitlab.com/kamcuk/armbuilder/armbuilder
  script:
  - pacman -Suy --noconfirm
  - pacman --noconfirm -S m4
  - make gitlab_arm_cdash

pages:
  stage: deploy
  image: ubuntu
  script:
  - *ubuntu_install_deps
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      graphviz doxygen
  - make gitlab_pages
  artifacts:
    paths:
    - public

