# .gitlab-ci.yml
---

image: "$CI_REGISTRY_IMAGE"
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CMAKE_BUILD_TYPE: Release

###############################################################################

build_builder:
  stage: build
  image: docker
  services:
    - docker:dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE || true
    - docker build --cache-from $CI_REGISTRY_IMAGE -t "$CI_REGISTRY_IMAGE" - < ./archlinux_builder.Dockerfile
    - docker push "$CI_REGISTRY_IMAGE"
  rules:
    - when: never
  #rules:
    #- if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      #when: on_success

###############################################################################

test_gcc:
  variables:
    CC: gcc
  script:
  - make valgrind
  - make test_project

test_project_add_subdirectory:
  script:
  - make test_project_add_subdirectory

test_gcc_sanitize:
  variables:
    CC: gcc
  script:
  - make MODE=sanitize test

test_clang:
  variables:
    CC: clang
  script:
  - make test

test_arm:
  script:
  - make SYSTEM=arm test

pages_build:
  script:
  - make gitlab_pages
  artifacts:
    paths:
    - public/
    expire_in: 1 week

###############################################################################

pages:
  stage: deploy
  image: busybox
  script:
  - find public -type f
  artifacts:
    paths:
    - public/
  only:
    - tags

