# .gitlab-ci.yml
---

image: registry.gitlab.com/kamcuk/builder
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CMAKE_BUILD_TYPE: Release

###############################################################################

icc_test:
  tags:
    - perun
  image:
    name: intel/oneapi-hpckit
    entrypoint: []
  variables:
    CC: icc
  script:
    - . /root/.oneapi_env_vars
    - apt update
    - apt install -y git libunistring-dev python-jinja2
    - make test

gcc_test:
  variables:
    CC: gcc
  script:
    - make valgrind
    - make test_project

gcc_sanitize_test:
  variables:
    CC: gcc
  script:
    - make sanitize

clang_test:
  variables:
    CC: clang
  script:
    - make test

arm_test:
  script:
    - make arm

project_add_subdirectory_test:
  script:
    - make test_project_add_subdirectory

alpine_test:
  image: alpine
  script:
    - apk add build-base make cmake ninja bash gcc py3-jinja2 libunistring-dev git
    - make test

pages_build:
  script:
    - make gitlab_pages
  artifacts:
    paths:
      - public/
    expire_in: 1 week

centos8:
  image: centos:8
  script:
    # https://stackoverflow.com/questions/70926799/centos-through-a-vm-no-urls-in-mirrorlist
    - sed -i -e "s|mirrorlist=|#mirrorlist=|g" -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-Linux-*
    # https://www.linode.com/community/questions/19087/how-do-i-install-libunistring-devel-on-centos-8
    - yum install dnf-plugins-core
    - yum -y install gcc cmake python3 python3-jinja2 git
    - make test

###############################################################################

pages:
  stage: deploy
  image: busybox
  script:
    - find public -type f
  artifacts:
    paths:
      - public/
  only:
    - tags
