# .gitlab-ci.yml
---

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

image: registry.gitlab.com/kamcuk/builder
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CMAKE_BUILD_TYPE: RelWithDebInfo

###############################################################################

.buildah_test:
  image: quay.io/buildah/stable
  variables:
    STORAGE_DRIVER: vfs
  script:
    - buildah build --target "${TARGET}" .

docker_target_tests:
  extends: .buildah_test
  parallel:
    matrix:
      - TARGET: ["gcc", "clang", "arm", "alpine", "icx", "lto", "valgrind", "nomalloc_nognu"]

gcc_arm64_test:
  extends: .buildah_test
  variables:
    TARGET: "gcc"
  tags:
    - saas-linux-small-arm64

lint_test:
  script:
    - pacman -Sy --noconfirm cpplint clang
    - make lint

gcc_sanitize_test:
  variables:
    CC: gcc
  script:
    - make sanitize

project_add_subdirectory_test:
  script:
    - make test_project_add_subdirectory

centos8_test:
  image: centos:8
  script:
    # https://stackoverflow.com/questions/70926799/centos-through-a-vm-no-urls-in-mirrorlist
    - sed -i -e "s|mirrorlist=|#mirrorlist=|g" -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-Linux-*
    # https://www.linode.com/community/questions/19087/how-do-i-install-libunistring-devel-on-centos-8
    - yum -y install dnf-plugins-core
    - yum config-manager --set-enabled powertools
    - yum -y install gcc cmake python3 python3-jinja2 git ninja-build libunistring-devel
    - make test

pages_build:
  script:
    - make gitlab_pages
  artifacts:
    paths:
      - public/
    expire_in: 1 week

###############################################################################

pages:
  stage: deploy
  image: busybox
  script:
    - find public -type f
  artifacts:
    paths:
      - public/
  only:
    - tags
