# .gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test_project:
  image: ubuntu
  script:
  - DEBIAN_FRONTEND=noninteractive apt-get update -y
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      make cmake m4 libc0.1-dev gcc valgrind ninja-build gcovr
  - make test_project

cdash_gcc:
  image: ubuntu
  script:
  - DEBIAN_FRONTEND=noninteractive apt-get update -y
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      make cmake m4 libc0.1-dev gcc valgrind ninja-build gcovr
  - make gitlab_gcc_cdash

cdash_clang:
  image: ubuntu
  script:
  - DEBIAN_FRONTEND=noninteractive apt-get update -y
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      make cmake m4 libc0.1-dev clang valgrind ninja-build gcovr
  - make gitlab_clang_cdash

cdash_arm:
  image: registry.gitlab.com/kamcuk/armbuilder/armbuilder
  script:
  - pacman -S m4
  - make gitlab_arm_cdash

pages:
  image: ubuntu
  script:
  - DEBIAN_FRONTEND=noninteractive apt-get update -y
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
      make cmake m4 libc0.1-dev gcc valgrind ninja-build gcovr
      graphiz doxygen
  - make doxygen
  artifacts:
    paths:
    - public

