variables:
  GIT_SUBMODULE_STRATEGY: recursive

on_gcc:
  image: gcc
  script:
  - apt-get update -y
  - apt-get install -y cmake make gcc cppcheck valgrind m4 ninja-build gcovr
  - make gitlab-ci
  
pages:
  image: alpine
  script:
  - apk update
  - apk add make doxygen bash m4 cmake make gcc graphviz
  - make doxygen
  artifacts:
    paths:
    - public

