# .gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  image: gcc
  script:
  - apt-get update -y
  - apt-get install -y cmake make gcc cppcheck valgrind m4 ninja-build gcovr
  - make gitlab_test
  
cdash:
  image: gcc
  script:
  - apt-get update -y
  - apt-get install -y cmake make gcc cppcheck valgrind m4 ninja-build gcovr
  - make gitlab_cdash

clang_test:
  image: ubuntu
  script:
  - apt-get update -y
  - apt-get install -y cmake make clang cppcheck valgrind m4 ninja-build gcovr
  - make gitlab_clang_test

arm_test:
  image: registry.gitlab.com/kamcuk/armbuilder/armbuilder
  - make gitlab_arm_test

arm_cdash:
  image: registry.gitlab.com/kamcuk/armbuilder/armbuilder
  - make gitlab_arm_cdash

pages:
  image: gcc
  script:
  - apt-get update -y
  - apt-get install -y cmake make gcc cppcheck valgrind m4 ninja-build gcovr dot
  - make doxygen
  artifacts:
    paths:
    - public

