cmake_minimum_required(VERSION 3.11)

#set(regex_start "[ \t]*_yIO_ERROR_START,([ \t]*//[ \t]*.* )?")
#set(regex       "[ \t]*(YIO_ERROR_[_A-Z]*),[ \t]*//[ \t]*(\".*\")")
#set(regex_stop  "[ \t]*_yIO_ERROR_STOP,([ \t]*//[ \t]*.* )?")
#
#file(STRINGS ${CMAKE_CURRENT_LIST_DIR}/yio_error.h input REGEX
#	"^(${regex_start}|${regex_stop}|${regex})$"
#)

if(NOT EXISTS "${INPUT}")
	message(FATAL_ERROR "File ${INPUT} Does not exists")
endif()
if("${OUTPUT}" STREQUAL "")
	message(FATAL_ERROR "OUTPUT is empty")
endif()
message(STATUS "Generating ${OUTPUT} from ${INPUT}")

set(regex "[ \t]*(YIO_ERROR_.*)([ \t]*=[^,]*)?,[ \t]*///[ \t]*GEN[ \t]*(\".*\")")
file(STRINGS "${INPUT}" input REGEX ".*")
message(STATUS "${input}")
file(STRINGS "${INPUT}" input REGEX "^${regex}")

if(NOT input)
	message(FATAL_ERROR "ERROR: no input ${input}")
endif()

set(str)
foreach(i IN LISTS input)
#	if(i MATCHES "^[ \t]*enum[ \t]*_yIO_errors_e[ \t]*{[ \t]*$")
#		set(start_found TRUE)
#	endif()
#	if(i MATCHES "^[ \t]*}[ \t]*;[ \t]*$")
#		break()
#	endif()
#	if(NOT start_found)
#		continue()
#	endif()

	string(REGEX REPLACE "^${regex}" "\t[\\1 - _yIO_ERROR_START - 1] =\n\t\t\\3," tmp ${i})
	string(APPEND str "${tmp}\n")
endforeach()

if(NOT str)
	message(FATAL_ERROR "error 2")
endif()

file(WRITE "${OUTPUT}" "
/**
 * @file yio_error_messages_gen.h *
 * DO NOT EDIT THIS FILE!
 * This file was autogenerated by yio_error_messages_gen.cmake script
 * from yio_error.h file.
 */
#if 0
#include \"yio_error_messages_gen.cmake\"
#endif
#include \"yio_error.h\"

static const char * const _yIO_error_messages[] = {
${str}};

"
)
