#!/bin/bash
set -euo pipefail

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 \"C CODE\""
    exit 1
fi

# Enable verbose if V=1
[[ "${V:-}" == "1" ]] && set -x

CODE="$*"

rm -f _build/SdccDebug/bin/yio_testprogram.ihx

# Build the testprogram target with PRESET=sdcc
env PRESET=sdcc TESTPROGRAM="$CODE" make .build_yio_testprogram

[[ -e _build/SdccDebug/bin/yio_testprogram.ihx ]]

ABORT_ADDR=0x$(grep -w "_abort" _build/SdccDebug/bin/yio_testprogram.map | awk '{print $2}')

# Run it in the simulator
{
    set -x
    timeout -v 5s s51 -q -Sout=- \
        -I 'if=rom[0x0000-0xffff]' \
        -I "if=xram[0xffff]" \
        -G _build/SdccDebug/bin/yio_testprogram.ihx <&-
} | cat
