#!/bin/bash
set -euo pipefail

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 \"C CODE\""
    exit 1
fi

# Enable verbose if V=1
[[ "${V:-}" == "1" ]] && set -x

CODE="$*"

rm -f _build/SdccDebug/bin/yio_testprogram.ihx

# Build the testprogram target with PRESET=sdcc
env PRESET=sdcc TESTPROGRAM="$CODE" make .build_yio_testprogram

# Run it in the simulator
set -x
timeout 30s s51 -Sout=- -I "if=xram[0xffff]" -G _build/SdccDebug/bin/yio_testprogram.ihx
