# Global defaults for C++ (used as the base language for Yio)
defaultSource=etc/examples/yio_example.c

# compilers=yio_gcc:yio_clang:yio_arm:yio_stm8
compilers=yio_gcc
defaultCompiler=yio_gcc

compiler.yio_gcc.exe=/usr/bin/gcc
compiler.yio_gcc.name=GCC (with Yio)
compiler.yio_gcc.options=-O2 -fplugin=/usr/local/lib/yio_gcc_fstring_plugin.so -Wl,--no-as-needed -Wl,--whole-archive -lm -lyio -lunistring -Wl,--no-whole-archive -ffunction-sections -fdata-sections  -Wl,--gc-sections

# compiler.yio_clang.exe=/usr/bin/clang
# compiler.yio_clang.name=Clang (with Yio)
# compiler.yio_clang.options=-O2 -fplugin=/usr/local/lib/yio_clang_fstring_plugin.so -lyio -lunistring
#
# compiler.yio_arm.exe=/usr/bin/arm-none-eabi-gcc
# compiler.yio_arm.name=ARM GCC (with Yio)
# compiler.yio_arm.options=-mthumb -mcpu=cortex-m3 -mfloat-abi=soft -Os -ffunction-sections -fdata-sections -ggdb3 -Wl,--no-as-needed -lyio --specs=rdimon.specs --specs=nosys.specs -u_printf_float -Wl,--gc-sections

# compiler.yio_stm8.exe=/usr/bin/sdcc
# compiler.yio_stm8.name=SDCC STM8 (with Yio)
# compiler.yio_stm8.options=-mstm8 --model-large --stack-auto --less-pedantic -DNDEBUG -Dstatic_assert=_Static_assert --opt-code-size --peep-return --nogcse -Wl,--no-as-needed -lyio
