compilers=yio_gcc:yio_clang

compiler.yio_gcc.exe=/usr/bin/gcc
compiler.yio_gcc.name=GCC (with Yio)
compiler.yio_gcc.options=-O2 -fplugin=/usr/local/lib/yio_fstring_plugin.so
compiler.yio_gcc.ldflags=-lyio
compiler.yio_gcc.includeDirs=/usr/local/include
compiler.yio_gcc.libDirs=/usr/local/lib
compiler.yio_gcc.lang=c++

compiler.yio_clang.exe=/usr/bin/clang
compiler.yio_clang.name=Clang (with Yio)
compiler.yio_clang.options=-O2
compiler.yio_clang.ldflags=-lyio
compiler.yio_clang.includeDirs=/usr/local/include
compiler.yio_clang.libDirs=/usr/local/lib
compiler.yio_clang.lang=c++
