#!/usr/bin/env python3

import argparse
import concurrent.futures
import datetime
import inspect
import jinja2
import jinja2.ext
import jinja2.meta
import logging
import os
import re
import sys

###############################################################################

log = logging.getLogger(os.path.basename(__file__))

j_FLOATS = [
    # N - "name"
    # G - "group". s = "standard", "f" = floats, "d" = decimals
    ["N", "G", "type", "math", "strto"],
    ["f", "s", "float", "f", "f"],
    ["d", "s", "double", "", "d"],
    ["l", "s", "long double", "l", "ld"],
    ["f16", "f", "_Float16", "f16", "f16"],
    ["f32", "f", "_Float32", "f32", "f32"],
    ["f64", "f", "_Float64", "f64", "f64"],
    ["f128", "f", "_Float128", "f128", "f128"],
    ["f32x", "fx", "_Float32x", "f32x", "f32x"],
    ["f64x", "fx", "_Float64x", "f64x", "f64x"],
    ["f128x", "fx", "_Float128x", "f128x", "f128x"],
    ["d32", "d", "_Decimal32", "d32", "d32"],
    ["d64", "d", "_Decimal64", "d64", "d64"],
    ["d128", "d", "_Decimal128", "d128", "d128"],
    ["d32x", "dx", "_Decimal32x", "d32x", "d32x"],
    ["d64x", "dx", "_Decimal64x", "d64x", "d64x"],
    ["d128x", "dx", "_Decimal128x", "d128x", "d128x"],
]

j_FLOATS = [
    # "invert" the table and replace N for 0, so it is j_FLOATS = [ {0:"f", "type": "float", etc..}, ... ]
    {**dict([(0, x[0])]), **{v: k for v, k in zip(j_FLOATS[0], x) if v != "N"}}
    for x in j_FLOATS[1:]
]


def j_range(*args) -> range:
    """Just like range, but start from 1 by default, and end exactly on end, instead of end -1"""
    if len(args) == 3:
        raise RuntimeError("too many arguments")
    if len(args) == 1:
        args = [1, args[0]]
    args = [int(x) for x in args]
    return range(args[0], args[1] + 1)


def j_match(value, regex) -> bool:
    return re.match(regex, str(value))


def j_fatal(value="fatal error"):
    raise Exception(str(value))


def j_frametemplate():
    template = None
    for frameInfo in inspect.stack():
        if frameInfo.frame.f_globals.get("__jinja_template__") is not None:
            template = frameInfo.frame.f_globals.get("__jinja_template__")
            break
    return template


class MyInclude(jinja2.ext.ExprStmtExtension):
    def parse(self, parser):
        node = super().parse(parser)
        return node


class MyEnvironment(jinja2.Environment):
    def __init__(self, srcdir, cachedir, defines, *args, **kwargs):
        super().__init__(
            loader=jinja2.FileSystemLoader(srcdir),
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True,
            extensions=[MyInclude],
            bytecode_cache=jinja2.FileSystemBytecodeCache(cachedir) if cachedir else None,
            *args, **kwargs
        )
        self.globals.update({
            "j_FLOATS": j_FLOATS,
            "j_MLVLS": int(defines.get("j_MLVLS", 32)),
            "j_range": j_range,
            "j_match": j_match,
            "j_fatal": j_fatal,
            "j_frametemplate": j_frametemplate,
        })
        self.filters.update({
            "j_range": j_range,
            "j_match": j_match,
        })
        self.preprocess = lambda source, name, filename: preprocess_source(source, filename)
        self.dependencies = []

    def get_template(self, name, parent=None, globals=None):
        template = super().get_template(name, parent, globals)
        if template.filename and template.filename not in self.dependencies:
            self.dependencies.append(template.filename)
        return template


def shoulddoline(source):
    return "# NOLINE" not in source


def preprocess_source(source, filename):
    if not filename.endswith(".c") and not filename.endswith(".h"):
        return source
    if "{% from 'library.jinja'" in source:
        return source
    imports = [
        "j_seq", "j_seqcomma", "j_seqdashcomma", "j_APPLY_IN",
        "j_APPLY", "j_FOREACHAPPLY", "j_FUNC",
    ]
    output = "{% from 'library.jinja' import " + ",".join(imports) + " %}\n"
    doline = shoulddoline(source)
    for lineno, line in enumerate(source.split("\n")):
        if "#line" in line:
            replacement = (f'#line {lineno + 2} "{filename}"') if doline else ""
            output += line.replace("#line", replacement) + "\n"
        else:
            output += line + "\n"
    return output


def postprocess(output, infilename, mode):
    if mode == "yio":
        output = output.replace("Ω", "").replace("π", "")
        output = re.sub("_yIO_TYPE_" + mode.upper(), "1", output)
    elif mode == "none":
        pass
    header = f"// Do not edit! Auto-generated by preprocess.py\n// mode = {mode}\n#line 1 \"{infilename}\"\n"
    return header + output


def save_if_changed(output, outfilename):
    if os.path.exists(outfilename):
        with open(outfilename, "r") as f:
            if f.read() == output:
                return False
    os.makedirs(os.path.dirname(outfilename), exist_ok=True)
    with open(outfilename, "w") as f:
        f.write(output)
    return True


def run_task(srcdir, cachedir, defines, mode, source, output_file):
    loader_paths = list(srcdir)
    template_name = source
    if os.path.isabs(source):
        loader_paths.insert(0, os.path.dirname(source))
        template_name = os.path.basename(source)

    env = MyEnvironment(loader_paths, cachedir, defines)
    template = env.get_template(template_name)
    render_vars = {
        "MODE": 1 if mode == "yio" else -1,
        "MODEX": 3 if mode == "yio" else -1,
        "TMODE": 1 if mode == "yio" else -1,
        "TMODEX": 3 if mode == "yio" else -1,
    }
    rendered = template.render(render_vars)
    final = postprocess(rendered, template.filename, mode)
    save_if_changed(final, output_file)
    return output_file, list(env.dependencies)


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("-S", "--srcdir", default=[], action="append")
    parser.add_argument("-D", "--define", default=[], action="append")
    parser.add_argument("-C", "--cachedir")
    parser.add_argument("-d", "--depfile")
    parser.add_argument("-m", "--mode", default="yio")
    parser.add_argument("-j", "--jobs", type=int, default=1)
    parser.add_argument("--debug", action="store_true") # Legacy
    parser.add_argument("--task", action="append", nargs=2, metavar=("SOURCE", "OUTPUT"))
    parser.add_argument("source", nargs='?')
    parser.add_argument("output", nargs='?')
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_arguments()
    defines = dict(d.split("=", 1) for d in args.define)
    tasks = args.task if args.task else ([[args.source, args.output]] if args.source else [])
    
    if not tasks:
        sys.exit(0)

    if args.cachedir:
        os.makedirs(args.cachedir, exist_ok=True)

    all_dependencies = {}
    if args.jobs > 1 and len(tasks) > 1:
        with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as ex:
            futures = [ex.submit(run_task, args.srcdir, args.cachedir, defines, args.mode, t[0], t[1]) for t in tasks]
            for future in concurrent.futures.as_completed(futures):
                out_file, deps = future.result()
                all_dependencies[out_file] = deps
    else:
        for t in tasks:
            out_file, deps = run_task(args.srcdir, args.cachedir, defines, args.mode, t[0], t[1])
            all_dependencies[out_file] = deps

    if args.depfile:
        os.makedirs(os.path.dirname(args.depfile), exist_ok=True)
        with open(args.depfile, "w") as f:
            for out_file, deps in sorted(all_dependencies.items()):
                deps_str = " ".join(sorted([os.path.realpath(d).replace(" ", "\\ ") for d in deps]))
                f.write(f"{os.path.realpath(out_file).replace(' ', '\\ ')}: {deps_str}\n")
