
## @def debug_variables([PREFIX prefix] [LEVEL FATAL_ERROR|SEND_ERROR|....] vars...)
function(debug_variables)
	cmake_parse_arguments(_debug_variables "" "PREFIX;LEVEL" "" ${ARGN})
	
	if(NOT DEFINED _debug_variables_LEVEL)
		set(_debug_variables_LEVEL STATUS)
	endif()
	set(_debug_variables_list "${_debug_variables_UNPARSED_ARGUMENTS}")
	list(SORT _debug_variables_list)
	foreach(_debug_variables_i IN LISTS _debug_variables_list)
		if(DEFINED ${_debug_variables_i})
			set(_debug_variables_val "=${${_debug_variables_i}}")
		else()
			set(_debug_variables_val " undefined")
		endif()
		message("${_debug_variables_LEVEL}" "${_debug_variables_PREFIX}${_debug_variables_i}${_debug_variables_val}")
	endforeach()
endfunction()

