cmake_minimum_required(VERSION 3.11)
project(sstest LANGUAGES C)
include(CTest)
add_library(sstest src/sstest.c src/sstest.h)
target_include_directories(sstest INTERFACE src)
set(SSTEST_ROOT "${CMAKE_SOURCE_DIR}" CACHE STRING "Root dir to remove from test filenames")
target_compile_definitions(sstest PRIVATE "SSTEST_ROOT=${SSTEST_ROOT}")
if(SSTEST_BUILD_TESTING)
  file(GLOB tests tests/*.c)
  message(STATUS "${tests}")
  foreach(nn IN LISTS tests)
    get_filename_component(nn ${nn} NAME_WE)
    add_executable(${nn} tests/${nn}.c)
    add_test(NAME ${nn} COMMAND ${nn})
    target_link_libraries(${nn} PRIVATE sstest)
    if(NOT "${nn}" STREQUAL "test2")
      set_tests_properties(${nn} PROPERTIES WILL_FAIL 1)
    endif()
  endforeach()
endif()


